import { Rank, Suit } from '../core/card';
import { cardOf } from './mocks';

export const FACE_DOWN = {
  KING_OF_SPADES: cardOf(Rank.K, Suit.Spades),
  KING_OF_CLUBS: cardOf(Rank.K, Suit.Clubs),
  KING_OF_HEARTS: cardOf(Rank.K, Suit.Hearts),
  QUEEN_OF_SPADES: cardOf(Rank.Q, Suit.Spades),
  QUEEN_OF_HEARTS: cardOf(Rank.Q, Suit.Hearts),
  JACK_OF_DIAMONDS: cardOf(Rank.J, Suit.Diamonds),
  JACK_OF_SPADES: cardOf(Rank.J, Suit.Spades),
  TEN_OF_SPADES: cardOf(Rank.Ten, Suit.Spades),
  TEN_OF_DIAMONDS: cardOf(Rank.Ten, Suit.Diamonds),
  NINE_OF_SPADES: cardOf(Rank.Nine, Suit.Spades),
  NINE_OF_DIAMONDS: cardOf(Rank.Nine, Suit.Diamonds),
  EIGHT_OF_SPADES: cardOf(Rank.Eight, Suit.Spades),
  EIGHT_OF_CLUBS: cardOf(Rank.Eight, Suit.Clubs),
  SEVEN_OF_SPADES: cardOf(Rank.Seven, Suit.Spades),
  SEVEN_OF_HEARTS: cardOf(Rank.Seven, Suit.Hearts),
  SIX_OF_SPADES: cardOf(Rank.Six, Suit.Spades),
  SIX_OF_DIAMONDS: cardOf(Rank.Six, Suit.Diamonds),
  SIX_OF_HEARTS: cardOf(Rank.Six, Suit.Hearts),
  FIVE_OF_SPADES: cardOf(Rank.Five, Suit.Spades),
  FIVE_OF_CLUBS: cardOf(Rank.Five, Suit.Clubs),
  FIVE_OF_DIAMONDS: cardOf(Rank.Five, Suit.Diamonds),
  FOUR_OF_SPADES: cardOf(Rank.Four, Suit.Spades),
  FOUR_OF_HEARTS: cardOf(Rank.Four, Suit.Hearts),
  FOUR_OF_DIAMONDS: cardOf(Rank.Four, Suit.Diamonds),
  FOUR_OF_CLUBS: cardOf(Rank.Four, Suit.Clubs),
  THREE_OF_SPADES: cardOf(Rank.Three, Suit.Spades),
  THREE_OF_CLUBS: cardOf(Rank.Three, Suit.Clubs),
  THREE_OF_HEARTS: cardOf(Rank.Three, Suit.Hearts),
  THREE_OF_DIAMONDS: cardOf(Rank.Three, Suit.Diamonds),
  TWO_OF_SPADES: cardOf(Rank.Two, Suit.Spades),
  TWO_OF_HEARTS: cardOf(Rank.Two, Suit.Hearts),
  TWO_OF_CLUBS: cardOf(Rank.Two, Suit.Clubs),
  TWO_OF_DIAMONDS: cardOf(Rank.Two, Suit.Diamonds),
  ACE_OF_SPADES: cardOf(Rank.A, Suit.Spades),
  ACE_OF_HEARTS: cardOf(Rank.A, Suit.Hearts),
  ACE_OF_CLUBS: cardOf(Rank.A, Suit.Clubs),
};

export const FACE_UP = {
  KING_OF_SPADES: cardOf(Rank.K, Suit.Spades, true),
  KING_OF_CLUBS: cardOf(Rank.K, Suit.Clubs, true),
  KING_OF_HEARTS: cardOf(Rank.K, Suit.Hearts, true),
  QUEEN_OF_SPADES: cardOf(Rank.Q, Suit.Spades, true),
  QUEEN_OF_HEARTS: cardOf(Rank.Q, Suit.Hearts, true),
  JACK_OF_DIAMONDS: cardOf(Rank.J, Suit.Diamonds, true),
  JACK_OF_SPADES: cardOf(Rank.J, Suit.Spades, true),
  TEN_OF_SPADES: cardOf(Rank.Ten, Suit.Spades, true),
  TEN_OF_DIAMONDS: cardOf(Rank.Ten, Suit.Diamonds, true),
  NINE_OF_SPADES: cardOf(Rank.Nine, Suit.Spades, true),
  NINE_OF_DIAMONDS: cardOf(Rank.Nine, Suit.Diamonds, true),
  EIGHT_OF_SPADES: cardOf(Rank.Eight, Suit.Spades, true),
  EIGHT_OF_CLUBS: cardOf(Rank.Eight, Suit.Clubs, true),
  SEVEN_OF_SPADES: cardOf(Rank.Seven, Suit.Spades, true),
  SEVEN_OF_HEARTS: cardOf(Rank.Seven, Suit.Hearts, true),
  SIX_OF_SPADES: cardOf(Rank.Six, Suit.Spades, true),
  SIX_OF_DIAMONDS: cardOf(Rank.Six, Suit.Diamonds, true),
  SIX_OF_HEARTS: cardOf(Rank.Six, Suit.Hearts, true),
  FIVE_OF_SPADES: cardOf(Rank.Five, Suit.Spades, true),
  FIVE_OF_CLUBS: cardOf(Rank.Five, Suit.Clubs, true),
  FIVE_OF_DIAMONDS: cardOf(Rank.Five, Suit.Diamonds, true),
  FOUR_OF_SPADES: cardOf(Rank.Four, Suit.Spades, true),
  FOUR_OF_HEARTS: cardOf(Rank.Four, Suit.Hearts, true),
  FOUR_OF_CLUBS: cardOf(Rank.Four, Suit.Clubs, true),
  FOUR_OF_DIAMONDS: cardOf(Rank.Four, Suit.Diamonds, true),
  THREE_OF_SPADES: cardOf(Rank.Three, Suit.Spades, true),
  THREE_OF_CLUBS: cardOf(Rank.Three, Suit.Clubs, true),
  THREE_OF_HEARTS: cardOf(Rank.Three, Suit.Hearts, true),
  THREE_OF_DIAMONDS: cardOf(Rank.Three, Suit.Diamonds, true),
  TWO_OF_SPADES: cardOf(Rank.Two, Suit.Spades, true),
  TWO_OF_HEARTS: cardOf(Rank.Two, Suit.Hearts, true),
  TWO_OF_CLUBS: cardOf(Rank.Two, Suit.Clubs, true),
  TWO_OF_DIAMONDS: cardOf(Rank.Two, Suit.Diamonds, true),
  ACE_OF_SPADES: cardOf(Rank.A, Suit.Spades, true),
  ACE_OF_HEARTS: cardOf(Rank.A, Suit.Hearts, true),
  ACE_OF_CLUBS: cardOf(Rank.A, Suit.Clubs, true),
};
